[module]
  [module.hugoVersion]
    min = "0.128.0"

# Output formats for Hedgerules.
# The theme defines these so sites that import it get them automatically.
[outputFormats]
  [outputFormats.hedgeheaders]
    baseName = "_hedge_headers"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
  [outputFormats.hedgeredirects]
    baseName = "_hedge_redirects"
    isPlainText = true
    mediaType = "text/plain"
    notAlternative = true
